### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by faisalakb**
In this leaderboard project apply following things :100: 
- Basic leaderboard setup :+1: 
- webpack setup :+1: 
- Linters setup :+1:

### CODE REVIEW

**Review by Gambit142 — COMMENTED** [review]
Hi @faisalakb 👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Your project was invalidated for the following reasons:
- You pushed `node_modules` to the remote repository instead of git ignoring it 
- You did not set up linters for this project. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by DammyShittu — COMMENTED** [review]
Hi @faisalakb,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### 1. In your readme documentation headers, the following links are not well documented: live demo and video presentation. If you have nothing for these links, kindly remove them and the live demo section.

### 2. The deployment header link does not take me to the deployment section. Kindly fix that as well.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rica213 — APPROVED** [review]
# 🟢 STATUS: APPROVED
Hi Faisal
My name is Larissa. I am your code reviewer 🥰

The setup of your project is complete 🛸 🛸 
- All Webpack-related packages are included in package.json ✅  
- Has `npm run ?` scripts like `build`, and `start` in package.json ✅ 
- HTML code looks like in the [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/images/leaderboard_wireframe.png) ✅ 
Congratulations! 🎉 



## Highlights

- [ ] Correct Gitflow ✔️ 
- [ ] No Linters errors ✔️ 
- [ ] Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
Thanks for the review

**Pull request merged**
